import { fetchTrending } from "./github";
import type { Repo } from "./types";

const TRENDING_TTL_MS = 5 * 60 * 1000; // 5 min — same TTL as the repos route used before (D-08)

// Max cache entries to prevent unbounded growth if many distinct keys are ever
// generated by the cron or UI. Each entry is a small Repo[] (<=100 items), so
// this is a memory-safety guard, not a business constraint.
const CACHE_MAX_ENTRIES = 500;

type Params = {
  topic?: string;
  query?: string;
  since?: string;
  page?: number;
  perPage?: number;
};

// Module-level TTL cache. Key = normalized topic|query|since|page|perPage (D-08).
const cache = new Map<string, { at: number; data: Repo[] }>();

// In-flight coalescing map: concurrent identical keys share ONE upstream call (D-09).
const inflight = new Map<string, Promise<Repo[]>>();

/** Normalize caller params to a stable cache key (lowercased topic per D-08). */
function keyOf(p: Params): string {
  const topic = (p.topic ?? "").trim().toLowerCase();
  const query = (p.query ?? "").trim();
  const since = (p.since ?? "").slice(0, 10);
  const page = p.page ?? 1;
  const perPage = p.perPage ?? 30;
  return `${topic}|${query}|${since}|${page}|${perPage}`;
}

/**
 * Cached, request-coalescing wrapper around fetchTrending.
 *
 * - Serves results from the module-level TTL cache when the key is fresh.
 * - Coalesces concurrent identical calls so only ONE upstream GitHub call is made (D-09).
 * - Caches ONLY non-empty results — a transient rate-limited/aborted [] does not
 *   stick for the full TTL, and the next call will retry fetchTrending (D-10).
 * - fetchTrending's signature, 5-tier search, and AbortSignal fail-fast are UNCHANGED (D-07).
 */
export async function fetchTrendingCached(p: Params = {}): Promise<Repo[]> {
  const key = keyOf(p);

  // Cache hit: serve within TTL.
  const hit = cache.get(key);
  if (hit && Date.now() - hit.at < TRENDING_TTL_MS) return hit.data;

  // In-flight hit: coalesce with the already-pending upstream call (D-09).
  const pending = inflight.get(key);
  if (pending) return pending;

  // Cold or expired: fire one upstream call.
  const promise = (async () => {
    const data = await fetchTrending(p);
    if (data.length > 0) {
      // Evict oldest entry if the map is at capacity (bounded growth guard).
      if (cache.size >= CACHE_MAX_ENTRIES) {
        const oldestKey = cache.keys().next().value;
        if (oldestKey !== undefined) cache.delete(oldestKey);
      }
      cache.set(key, { at: Date.now(), data }); // cache non-empty only (D-10)
    }
    return data;
  })().finally(() => {
    inflight.delete(key); // always clean up the in-flight slot
  });

  inflight.set(key, promise);
  return promise;
}
