// Auto-generated cloudflare environment type declarations.
// Generated by: wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts
// Binding "DB" corresponds to the D1 database in wrangler.jsonc.
//
// Any changes here must match the bindings in wrangler.jsonc.

interface CloudflareEnv {
  DB: D1Database;
  // Shared trending-repo cache (kv_namespaces[].binding in wrangler.jsonc).
  TRENDING_CACHE: KVNamespace;
}
